name: CI build

on: 
  schedule:
    - cron: '0 12 * * *'  # this will be triggered on 12pm (UTC) each day 
  push:
    branches:
      - main

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        firefox: [ '96.0.2']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python "3.10"
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install Poetry
      uses: Gr1N/setup-poetry@v7
    - run: poetry --version
    - name: Install Dependencies
      run: poetry install
    - name: Execute Crawler
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
      run: poetry run python jobs/yt_api.py
        
  